// <auto-generated />
using System;
using Investimento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investimento.Data.Migrations
{
    [DbContext(typeof(InvestimentoDbContext))]
    partial class InvestimentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Investimento.Core.Fundo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<decimal>("IIM");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Fundos");
                });

            modelBuilder.Entity("Investimento.Core.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DtMovimentacao");

                    b.Property<Guid?>("FundosId");

                    b.Property<string>("Nome");

                    b.Property<decimal>("VlMovimentacao");

                    b.Property<int>("tipomovimentacao");

                    b.HasKey("Id");

                    b.HasIndex("FundosId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Investimento.Core.Movimentacao", b =>
                {
                    b.HasOne("Investimento.Core.Fundo", "Fundos")
                        .WithMany()
                        .HasForeignKey("FundosId");
                });
#pragma warning restore 612, 618
        }
    }
}
